# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Builds Apple iOS project using CI progress

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:
    name: Build iOS Project
    runs-on: macos-latest
    
    steps:
    - name: Checkout from repository
      uses: actions/checkout@v3

    - name: List available Xcode versions
      run: ls /Applications | grep Xcode

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
    - name: Check Current Xcode Path
      run: xcode-select -p

    - name: List directory contents
      run: ls -R

    # - name: open access
    #   run: chmod -R 755 /Users/runner/work/ThreadsTutorials/ThreadsTutorials/ThreadsTutorials.xcodeproj

    - name: Build
      run: sudo xcodebuild -project "./ThreadsTutorials.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" CODE_SIGN_STYLE=Manual CODE_SIGNING_REQUIRED=NO DEVELOPMENT_TEAM= -sdk iphonesimulator -scheme ThreadsTutorials PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER= -configuration Debug clean build
          # |
          # proj_path=$(pwd)
          # sudo xcodebuild -project "$proj_path/ThreadsTutorials.xcodeproj" clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4 " -allowProvisioningUpdates
          # ls -al .
          # pwd
          # xcodebuild -project ThreadsTutorials.xcodeproj clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"
          # xcodebuild -project ThreadsTutorials.xcodeproj clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"
          # xcodebuild -scheme ThreadsTutorials clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"

    - name: build Archive
      run: |
          sudo xcodebuild -scheme "ThreadsTutorials" \
          -archivePath ./build/ThreadsTutorials.xcarchive \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"  \
          CODE_SIGN_STYLE=Manual CODE_SIGNING_REQUIRED=NO DEVELOPMENT_TEAM= PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER= 
          # |
          # -destination generic/platform=iOS \
          # clean archive

    - name: export ipa
      # env:
      #     EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      run: |
          # EXPORT_OPTS_PATH=./ExportOptions.plist
          # echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath ./build/ThreadsTutorials.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./build

    # - name: List out project from Apple iOS xcode project
    #   run: xcodebuild -list -project ThreadsTutorials.xcodeproj

    # - name: Clean iOS project
    #   run: xcodebuild clean

    # - name: Archive the iOS Project
    #   run: xcodebuild archive -scheme ThreadsTutorials -sdk iphoneos -allowProvisioningUpdates -archivePath /Users/MiniHsieh/Desktop/Archive/ThreadsTutorials.xcarchive

