# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Builds Apple iOS project using CI progress

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:
    name: Build iOS Project
    runs-on: macos-latest
    
    steps:
    - name: Checkout from repository
      uses: actions/checkout@v4

    - name: List available Xcode versions
      run: ls /Applications | grep Xcode

    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Check Current Xcode Path
      run: xcode-select -p

    - name: List directory contents
      run: ls -R

    - name: Build
      run: |
          proj_path=$(pwd)
          sudo xcodebuild xcodebuild -project "$proj_path/ThreadsTutorials.xcodeproj" clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"
          # ls -al .
          # pwd
          # xcodebuild -project ThreadsTutorials.xcodeproj clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"
          # xcodebuild -project ThreadsTutorials.xcodeproj clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"
          # xcodebuild -scheme ThreadsTutorials clean build -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4"

    - name: build Archive
      run: |
          xcodebuild -scheme "ThreadsTutorials" \
          -archivePath ./build/ThreadsTutorials.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive

    - name: export ipa
      # env:
      #     EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      run: |
          # EXPORT_OPTS_PATH=./ExportOptions.plist
          # echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath ./build/ThreadsTutorials.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./build

    # - name: List out project from Apple iOS xcode project
    #   run: xcodebuild -list -project ThreadsTutorials.xcodeproj

    # - name: Clean iOS project
    #   run: xcodebuild clean

    # - name: Archive the iOS Project
    #   run: xcodebuild archive -scheme ThreadsTutorials -sdk iphoneos -allowProvisioningUpdates -archivePath /Users/MiniHsieh/Desktop/Archive/ThreadsTutorials.xcarchive

